import { BackgroundOption, GlassSettings, Preset } from './types';

export const DEFAULT_GLASS_SETTINGS: GlassSettings = {
  width: 300,
  height: 200,
  radius: 60,
  thickness: 50,
  bezel: 60,
  ior: 3.0,
  dispersion: 1.8,
  blur: 1.5,
  specular: 0.55,
  tint: 8,
  shadow: 0.5,
  wobbleIntensity: 0.65,
  floatingEnabled: true,
  rippleOnClick: true,
  lightFollowsMouse: true,
};

export const BACKGROUND_OPTIONS: BackgroundOption[] = [
  {
    id: 'deep-black-orbs',
    name: 'Deep Void & 3D Orbs',
    url: 'scene://deep-black-orbs',
  },
  {
    id: 'studio-white-orbs',
    name: 'Pure White & 3D Orbs',
    url: 'scene://studio-white-orbs',
  },
  {
    id: 'living-room',
    name: 'Modern Living Room',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpqTFc884FyMsQhl9lwUt32PFm3dZece4gVanjFehViV9s7KCfEK0e8_SaZf3aknQlPSB62rfFykmn7hJHsN063jFhhSEoTxgYjK4SrD0NVKLq6csnTGphx6-PlqBQJbs--1FlhR_cxo-930lt1zpmbxgzpn8GInD3twDZKIOHDxnAlpQ83VPkgmV1ARPuJL7dpgdhAjV-WarCfim6xKBGZOwZU2w9iHkz7C7mi9lTN2SX4ka3OEjgUA',
  },
  {
    id: 'japandi-studio',
    name: 'Japandi Warm Studio',
    url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1920&q=85',
  },
  {
    id: 'minimalist-loft',
    name: 'Minimalist Architecture',
    url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1920&q=85',
  },
  {
    id: 'botanical-conservatory',
    name: 'Botanical Conservatory',
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1920&q=85',
  },
];

export const PRESETS: Preset[] = [
  {
    id: 'default-liquid',
    name: 'Default Liquid',
    description: 'Balanced optical glass with chromatic bevel and organic wobble',
    settings: {
      width: 300,
      height: 200,
      radius: 60,
      thickness: 50,
      bezel: 60,
      ior: 3.0,
      dispersion: 1.8,
      blur: 1.5,
      specular: 0.55,
      tint: 8,
      wobbleIntensity: 0.65,
    },
  },
  {
    id: 'molten-jelly',
    name: 'Molten Jelly',
    description: 'Ultra-pliable fluid droplet with exaggerated elastic wobble',
    settings: {
      width: 260,
      height: 260,
      radius: 130,
      thickness: 75,
      bezel: 85,
      ior: 3.6,
      dispersion: 2.8,
      blur: 0.8,
      specular: 0.75,
      tint: 12,
      wobbleIntensity: 1.0,
    },
  },
  {
    id: 'vision-glass',
    name: 'Vision Glass',
    description: 'Pristine, crystal-clear spatial computing glass plate',
    settings: {
      width: 380,
      height: 220,
      radius: 48,
      thickness: 35,
      bezel: 38,
      ior: 1.9,
      dispersion: 1.2,
      blur: 0.5,
      specular: 0.68,
      tint: 4,
      wobbleIntensity: 0.25,
    },
  },
  {
    id: 'prism-magnifier',
    name: 'Prism Magnifier',
    description: 'High refractive index crystal with intense spectral dispersion',
    settings: {
      width: 280,
      height: 280,
      radius: 140,
      thickness: 85,
      bezel: 95,
      ior: 4.5,
      dispersion: 4.2,
      blur: 0.0,
      specular: 0.8,
      tint: 6,
      wobbleIntensity: 0.3,
    },
  },
  {
    id: 'frosted-quartz',
    name: 'Frosted Quartz',
    description: 'Matte frosted surface with soft diffused refraction',
    settings: {
      width: 320,
      height: 200,
      radius: 50,
      thickness: 45,
      bezel: 50,
      ior: 2.4,
      dispersion: 0.8,
      blur: 9.0,
      specular: 0.45,
      tint: 18,
      wobbleIntensity: 0.4,
    },
  },
];
